const SUBJECTS = [
  {id:"physics", name:"Physics", tag:"QCAA \u00b7 Physics", icon:"\u269b", qcaaLabel:"Physics", qcaaUrl:"https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/sciences/physics", accent:"#8FC1E3", storageKey:"tracker-v2::physics", dotpoints:PHYSICS_DP},
  {id:"specialist-maths", name:"Specialist Maths", tag:"QCAA \u00b7 Spec Maths", icon:"\ud83d\udcd0", qcaaLabel:"Specialist Mathematics", qcaaUrl:"https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/mathematics/specialist-mathematics", accent:"#B79CED", storageKey:"tracker-v2::specialist-maths", dotpoints:SPECIALIST_MATHS_DP},
  {id:"chemistry", name:"Chemistry", tag:"QCAA \u00b7 Chemistry", icon:'<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" style="display:inline-block;vertical-align:-0.14em"><path d="M9.5 3h5"/><path d="M10.5 3v6.2L4.6 19.3A1.6 1.6 0 0 0 6 21.7h12a1.6 1.6 0 0 0 1.4-2.4L13.5 9.2V3"/><path d="M6.8 15.5h10.4l2.2 3.8A1.6 1.6 0 0 1 18 21.7H6A1.6 1.6 0 0 1 4.6 19.3z" fill="currentColor" fill-opacity=".32" stroke="none"/></svg>', qcaaLabel:"Chemistry", qcaaUrl:"https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/sciences/chemistry", accent:"#6FBF9E", storageKey:"tracker-v2::chemistry", dotpoints:CHEMISTRY_DP},
  {id:"economics", name:"Economics", tag:"QCAA \u00b7 Economics", icon:"\ud83d\udcc8", qcaaLabel:"Economics", qcaaUrl:"https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/humanities-and-social-sciences/economics", accent:"#F0B15C", storageKey:"tracker-v2::economics", dotpoints:ECONOMICS_DP},
  {id:"methods", name:"Maths Methods", tag:"QCAA \u00b7 Methods", icon:"\u222b", qcaaLabel:"Mathematical Methods", qcaaUrl:"https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/mathematics/mathematical-methods", accent:"#F09BC0", storageKey:"tracker-v2::methods", dotpoints:METHODS_DP},
  {id:"biology", name:"Biology", tag:"QCAA \u00b7 Biology", icon:"\ud83e\uddec", qcaaLabel:"Biology", qcaaUrl:"https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/sciences/biology", accent:"#B7D957", storageKey:"tracker-v2::biology", dotpoints:BIOLOGY_DP}
];

const KEY_HINTS = {physics:'e.g. F = GMm/r²', 'specialist-maths':'e.g. z = r cis(θ)', chemistry:'e.g. Kc = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ', economics:'e.g. % change = (new − old) ÷ old × 100', methods:'e.g. d/dx eˣ = eˣ', biology:'e.g. N = M × n ÷ m'};
const STATUS_COLOR = {P:'#4C8F6B', K:'#DE9F35', D:'#C24A3E', none:'#3E5266'};
const STATUS_LABEL = {P:'Perfectly', K:'Kinda', D:"Don't know", none:'Unreviewed'};
